### ISSUE TITLE
awips breaking environment

### ISSUE THREAD

**Issue by jrleeman** [Unidata/unidata-python-workshop#348]
Python AWIPS install is killing the environment locally and on CI. I've moved it all to failing and removed from `environment.yml` in #347, but likely relevant/important to @mjames-upc as local workshops approach.

**Comment by jrleeman** [comment]
@mjames-upc - Looks like this is a change in the way our environment file needs to work. We now must specify that pip needs to be installed before then getting python-awips. It'll be fixed in #347, but I'll leave this open with a different title as the notebooks are in the failing directory as many are no longer passing CI and I assume you'll want those for the workshop.

**Comment by mjames-upc** [comment]
I have a PR at https://github.com/conda-forge/staged-recipes/pull/6759, so hopefully python-awips will be available on conda-forge soon. In the meantime, I looked again at the changes to environment.yml and still get the same error as before (pip is defined twice in your latest edit). It does appear that pip is installed before python-awips, as you say, and there is the `Successfully built python-awips` message in the result below, but the error is still seen.


in environment.yml

```
   - pip
   - pip:
     - python-awips
```

```
conda env update -f environment.yml 

conda env update -f environment.yml 
Solving environment: done

Downloading and Extracting Packages
pip-18.0             | 1.8 MB    | ################################################################################################################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting python-awips (from -r /Users/mjames/unidata-python-workshop/condaenv.pn_95g9y.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/3a/05/7d0c53f27af89b4dab569328acd5c6740cccd1f662edce1201fb4fc20bad/python-awips-18.1.2.tar.gz (166kB)
    100% |████████████████████████████████| 174kB 2.5MB/s 
Requirement already satisfied: numpy in /Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages (from python-awips->-r /Users/mjames/unidata-python-workshop/condaenv.pn_95g9y.requirements.txt (line 1)) (1.15.2)
Requirement already satisfied: six in /Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages (from python-awips->-r /Users/mjames/unidata-python-workshop/condaenv.pn_95g9y.requirements.txt (line 1)) (1.11.0)
Building wheels for collected packages: python-awips
  Running setup.py bdist_wheel for python-awips ... done
  Stored in directory: /Users/mjames/Library/Caches/pip/wheels/ad/15/e9/67c4cdb77e0f896d713f87e020d3dc98c21a8ae315ce7c2d8a
Successfully built python-awips
Exception:
Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in _dep_map
    return self.__dep_map
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2949, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; extra '"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 330, in run
    self._warn_about_conflicts(to_install)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 456, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 98, in check_install_conflicts
    package_set = create_package_set_from_installed()
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 41, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2871, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2881, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2942, in parse_requirements
    yield Requirement(line)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2951, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"

CondaValueError: pip returned an error

```

**Comment by jrleeman** [comment]
Strange - I got it to work once locally - anyhow, conda packages! 👍

**Comment by mjames-upc** [comment]
Yeah I'm finding it works now too, and trying to recreate the error and can not.  Removing and recreating the environment seems to have solved this, or something upstream was solved in the time us and others found this error. ¯\_(ツ)_/¯

**Comment by jrleeman** [comment]
![giphy](https://user-images.githubusercontent.com/325269/46362167-c3c30a00-c62c-11e8-9afd-0b750624258b.gif)

**Comment by jrleeman** [comment]
Oddly enough @dopplershift ran into a similar error from pip as well recently (lunch conversation).
